# Generated by Django 4.1.1 on 2022-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_remove_presence_etudiants_etudiant_presences'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='agenda',
            field=models.BooleanField(default=False),
        ),
    ]
