# Generated by Django 4.1.1 on 2022-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_etudiant_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='nom',
            field=models.CharField(blank=True, default='student', max_length=100, null=True),
        ),
    ]
