# Generated by Django 4.1.1 on 2022-10-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_presence_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='nom',
        ),
    ]
