# Generated by Django 4.1.1 on 2022-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_dateheure_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateheure',
            name='nom',
            field=models.CharField(default='not define', max_length=100),
            preserve_default=False,
        ),
    ]
