# Generated by Django 4.1.1 on 2022-10-28 15:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_dateheure_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateheure',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presence',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 10, 28, 15, 14, 44, 557880, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
