# Generated by Django 4.1.1 on 2022-10-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0009_alter_dateheure_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateheure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='created_at',
        ),
    ]
